support XXX seconds
StudistCorporation/fluent-plugin-timestream pull request #14
Opened 2021-05-12 11:57 UTC by studist-motoshi-takeda

Motivation:
Enable to write record which has more than seconds accuracy.
Amazon Timstream supports MILLISECONDS, MICROSECONDS, NANOSECONDS

Modifications:
Add 2 config item (time_unit, time_key)
Fix test and documents

2021-05-12 11:58 UTC, studist-motoshi-takeda commented on .rubocop.yml
> +  SuggestExtensions: false
Extension の文言がコード中に入ることがあったので無効化

2021-05-12 12:03 UTC, studist-motoshi-takeda commented on README.md
> -When writing Timestream records, `TimeUnit` is always set to `SECONDS`
メインの変更点はここだけ。他は大文字小文字の修正、改行の修正

2021-05-12 12:05 UTC, studist-motoshi-takeda commented on lib/fluent/plugin/out_timestream.rb
> +          time = record.delete(@time_key) unless @time_key.nil?
chunk に入る time は integer の値が入って float の値などは入れられなかった。
そのため milliseconds などを指定する場合はその単位に揃えた epoch time を record に作って、指定させるようにした。

2021-05-13 06:45 UTC, taurauko requested changes

2021-05-13 06:45 UTC, taurauko commented on README.md
> +The plugin ignores record when it has no dimensions.
謎のスペース残ってる
```suggestion
The plugin ignores record when it has no dimensions.
```

2021-05-13 06:45 UTC, taurauko commented on lib/fluent/plugin/out_timestream.rb
> +      # rubocop:disable Metrics/MethodLength
以前も言ったが守るつもりのないルールは緩めてもいい。

とはいえこれに関してeach_with_object使えば行数抑えられる。

2021-05-13 06:45 UTC, taurauko commented on lib/fluent/plugin/out_timestream.rb
> +      # rubocop:disable Metrics/MethodLength
```ruby
def create_timestream_records(chunk)
  chunk.each_with_object([]) do |(time, record), records|
    time = record.delete(@time_key) unless @time_key.nil?
    dimensions, measure = create_timestream_dimensions_and_measure(record)
    records.push(create_timestream_record(dimensions, time, measure))
  rescue EmptyValueError, NoDimensionsError => e
    log.warn("ignored record due to #{e}")
    log.debug("ignored record details: #{record}")
  end
end
```

2021-05-13 06:49 UTC, studist-motoshi-takeda commented on README.md
> +The plugin ignores record when it has no dimensions.
ここは改行を入れたいので意図的に残しています。

2021-05-13 06:52 UTC, studist-motoshi-takeda commented on lib/fluent/plugin/out_timestream.rb
> +      # rubocop:disable Metrics/MethodLength
chunk は `Fluent::Plugin::Buffer::MemoryChunk` なのですが、これが each_with_object もってないんです。。。
緩めるかは毎回悩んでます。。。

2021-05-13 08:55 UTC, taurauko commented on lib/fluent/plugin/out_timestream.rb
> +      # rubocop:disable Metrics/MethodLength
eachの実装次第だけど、 `each.with_object([])` とも書けるぜ？

2021-05-13 08:55 UTC, taurauko commented on README.md
> +The plugin ignores record when it has no dimensions.
改行とどう関係する？

2021-05-13 08:56 UTC, studist-motoshi-takeda commented on README.md
> +The plugin ignores record when it has no dimensions.
あれ、markdown って改行がスペース2つじゃなかったでしたっけ。
ローカルでPreviewで見ると反映されるんですが・・・

2021-05-13 09:02 UTC, studist-motoshi-takeda commented on lib/fluent/plugin/out_timestream.rb
> +      # rubocop:disable Metrics/MethodLength
> eachの実装次第だけど、 each.with_object([]) とも書けるぜ？

試してみましたが残念ながら無いようです。。

2021-05-14 05:24 UTC, taurauko commented on lib/fluent/plugin/out_timestream.rb
> +      # rubocop:disable Metrics/MethodLength
ブロック渡さない場合にそのeachの返り値教えてください

2021-05-14 05:40 UTC, taurauko commented on README.md
> +The plugin ignores record when it has no dimensions.
そういうことか

2021-05-14 05:45 UTC, taurauko commented on lib/fluent/plugin/out_timestream.rb
> +      # rubocop:disable Metrics/MethodLength
Kernel#openで包まれてるからか... reducerを切り出すことはできるがまぁじゃこれで...

2021-05-14 05:45 UTC, taurauko approved these changes

2021-05-14 05:49 UTC, merged